### ISSUE TITLE
按照用法解密出来的文件无法读取

### ISSUE THREAD

**Issue by PackageInstaller** [lambwheit/cocos2dx-xxtea-decryptor#2]
指令 `cocos2d.xxtea.decryptor.exe palmpi horcruxmatrix assets`
实例文件
[1013_hougebo_1.zip](https://github.com/lambwheit/cocos2dx-xxtea-decryptor/files/12709008/1013_hougebo_1.zip)

解密后的文件
[1013_hougebo_1.zip](https://github.com/lambwheit/cocos2dx-xxtea-decryptor/files/12709057/1013_hougebo_1.zip)

看了一下hex,是png格式的应该没错，就是无法预览，密钥也是对的(，但是lua文件解密成功能正常预览

细看了下，有一张图可能导出成功了（不确定？）
![image](https://github.com/lambwheit/cocos2dx-xxtea-decryptor/assets/80018096/88ec1a84-e035-4f78-8c1a-ab72055f0767)
![image](https://github.com/lambwheit/cocos2dx-xxtea-decryptor/assets/80018096/68c1240c-bf24-403d-ac3d-22e3024368dd)
[7_bg.zip](https://github.com/lambwheit/cocos2dx-xxtea-decryptor/files/12713631/7_bg.zip)

游戏是盲盒派对，现在在B站测试，能直接下
麻烦大佬帮忙看看吧

**Comment by lambwheit** [comment]
图/资产不能用我的软件，应为图/资产的加密算法和lua/js文件的加密算法不一样

**Comment by PackageInstaller** [comment]
那大佬能指路一下吗，我不知道该用什么好

**Comment by lambwheit** [comment]
可以发给我那个apk吗？我帮你看看

**Comment by PackageInstaller** [comment]
上传的[Google Drive](https://drive.google.com/file/d/1BIWss8qMURKbCL4BqKDFjCYAIkrLfMmY/view?usp=sharing)

**Comment by lambwheit** [comment]
![image](https://github.com/lambwheit/cocos2dx-xxtea-decryptor/assets/38606611/9ce24ea4-fa50-4015-a64f-da1117a6c192)

那一个是cocos2dx的文件？

**Comment by PackageInstaller** [comment]
libhcollege_matrix.so，应该是这个

**Comment by lambwheit** [comment]
好我等下帮你看吧

**Comment by PackageInstaller** [comment]
我是在这个so里面直接搜的加密头找的密钥，至于具体加密算法我没看，应该是图里面这个函数？
![image](https://github.com/lambwheit/cocos2dx-xxtea-decryptor/assets/80018096/05b98bda-946f-489f-8b06-23212239fc30)

**Comment by lambwheit** [comment]
just checked, xxtea is indeed not used for the assets in your application, you have to find where the image/sprite is loaded then reverse engineer from there to find out how it's decrypted or you could just dump the already decrypted files from memory using frida. cant really help cause all i see for the string horcruxmatrix is that it's only being used twice, once to get the lenght of the string and once to set the xxtea key and sign. sry cant help much as it will probably take up too much of my time

**Comment by bf179** [comment]
> 指令 `cocos2d.xxtea.decryptor.exe palmpi horcruxmatrix assets` 实例文件 [1013_hougebo_1.zip](https://github.com/lambwheit/cocos2dx-xxtea-decryptor/files/12709008/1013_hougebo_1.zip)
> 
> 解密后的文件 [1013_hougebo_1.zip](https://github.com/lambwheit/cocos2dx-xxtea-decryptor/files/12709057/1013_hougebo_1.zip)
> 
> 看了一下hex,是png格式的应该没错，就是无法预览，密钥也是对的(，但是lua文件解密成功能正常预览
> 
> 细看了下，有一张图可能导出成功了（不确定？） ![image](https://user-images.githubusercontent.com/80018096/270299322-88ec1a84-e035-4f78-8c1a-ab72055f0767.png) ![image](https://user-images.githubusercontent.com/80018096/270299152-68c1240c-bf24-403d-ac3d-22e3024368dd.png) [7_bg.zip](https://github.com/lambwheit/cocos2dx-xxtea-decryptor/files/12713631/7_bg.zip)
> 
> 游戏是盲盒派对，现在在B站测试，能直接下 麻烦大佬帮忙看看吧

佬解出来了吗:cry:而且这游戏好像也没有其他人在解包的样子:broken_heart:

**Comment by PackageInstaller** [comment]
> > 指令 `cocos2d.xxtea.decryptor.exe palmpi horcruxmatrix assets` 实例文件 [1013_hougebo_1.zip](https://github.com/lambwheit/cocos2dx-xxtea-decryptor/files/12709008/1013_hougebo_1.zip)
> > 解密后的文件 [1013_hougebo_1.zip](https://github.com/lambwheit/cocos2dx-xxtea-decryptor/files/12709057/1013_hougebo_1.zip)
> > 看了一下hex,是png格式的应该没错，就是无法预览，密钥也是对的(，但是lua文件解密成功能正常预览
> > 细看了下，有一张图可能导出成功了（不确定？） ![image](https://user-images.githubusercontent.com/80018096/270299322-88ec1a84-e035-4f78-8c1a-ab72055f0767.png) ![image](https://user-images.githubusercontent.com/80018096/270299152-68c1240c-bf24-403d-ac3d-22e3024368dd.png) [7_bg.zip](https://github.com/lambwheit/cocos2dx-xxtea-decryptor/files/12713631/7_bg.zip)
> > 游戏是盲盒派对，现在在B站测试，能直接下 麻烦大佬帮忙看看吧
> 
> 佬解出来了吗😢而且这游戏好像也没有其他人在解包的样子💔

解出来了，换这个[工具](https://github.com/zzwlpx/DecApkTools)或是参照cocos的xxtea部分代码即可

**Comment by bf179** [comment]
> > > 指令 `cocos2d.xxtea.decryptor.exe palmpi horcruxmatrix assets` 实例文件 [1013_hougebo_1.zip](https://github.com/lambwheit/cocos2dx-xxtea-decryptor/files/12709008/1013_hougebo_1.zip)
> > > 解密后的文件 [1013_hougebo_1.zip](https://github.com/lambwheit/cocos2dx-xxtea-decryptor/files/12709057/1013_hougebo_1.zip)
> > > 看了一下hex,是png格式的应该没错，就是无法预览，密钥也是对的(，但是lua文件解密成功能正常预览
> > > 细看了下，有一张图可能导出成功了（不确定？） ![image](https://user-images.githubusercontent.com/80018096/270299322-88ec1a84-e035-4f78-8c1a-ab72055f0767.png) ![image](https://user-images.githubusercontent.com/80018096/270299152-68c1240c-bf24-403d-ac3d-22e3024368dd.png) [7_bg.zip](https://github.com/lambwheit/cocos2dx-xxtea-decryptor/files/12713631/7_bg.zip)
> > > 游戏是盲盒派对，现在在B站测试，能直接下 麻烦大佬帮忙看看吧
> > 
> > 
> > 佬解出来了吗😢而且这游戏好像也没有其他人在解包的样子💔
> 
> 解出来了，换这个[工具](https://github.com/zzwlpx/DecApkTools)或是参照cocos的xxtea部分代码即可

解密成功了，感谢佬。这游戏cg真心可爱

**Comment by IlluminatiWave** [comment]
![1013_hougebo_1](https://github.com/lambwheit/cocos2dx-xxtea-decryptor/assets/42191299/81fec452-02e5-4282-9902-43b9c4cf649b)

https://github.com/lambwheit/cocos2dx-xxtea-decryptor/issues/4#issuecomment-1879829567 (BUG FIXED)
